# Generated by Django 5.1 on 2024-09-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website_name", models.CharField(max_length=255)),
                ("website_fav", models.TextField(blank=True, null=True)),
                ("website_logo", models.TextField(blank=True, null=True)),
                ("website_feature1", models.TextField(blank=True, null=True)),
                ("website_feature2", models.TextField(blank=True, null=True)),
                ("website_scrollimg1", models.TextField(blank=True, null=True)),
                ("website_scrollimg2", models.TextField(blank=True, null=True)),
                ("website_scrollimg3", models.TextField(blank=True, null=True)),
                ("website_scrollimg4", models.TextField(blank=True, null=True)),
                ("website_scrollimg5", models.TextField(blank=True, null=True)),
                ("website_scrollimg6", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
