# Generated by Django 5.1 on 2024-10-03 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(blank=True, max_length=255, null=True)),
                ('about_description', models.TextField(blank=True, null=True)),
                ('about_image', models.TextField(blank=True, null=True)),
                ('history_image', models.TextField(blank=True, null=True)),
                ('history_text', models.TextField(blank=True, null=True)),
                ('owner_img', models.TextField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_img', models.TextField(blank=True, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fran_manager_img', models.TextField(blank=True, null=True)),
                ('fran_manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cook_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cook_img', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='website_baner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('about_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='dashboard.aboutsettings')),
            ],
        ),
    ]
