# Generated by Django 5.1 on 2024-10-04 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_aboutsettings_sitesettings_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutsettings",
            name="history_image",
        ),
        migrations.RemoveField(
            model_name="aboutsettings",
            name="history_text",
        ),
        migrations.DeleteModel(
            name="Achievement",
        ),
    ]
