# Generated by Django 5.1 on 2024-09-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_alter_subcategory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="items_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
