# Generated by Django 5.1 on 2024-09-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_alter_menuitem_items_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="items_image",
            field=models.TextField(),
        ),
    ]
