# Generated by Django 5.1 on 2024-10-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0004_alter_menuitem_items_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="items_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="items_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
